name: Generate and Commit Cosign Keys

on:
  workflow_dispatch:

jobs:
  generate-keys:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install cosign
        uses: sigstore/cosign-installer@v3.5.0
        with:
          cosign-release: 'v2.2.4'

      - name: Install OpenSSL
        run: sudo apt-get update && sudo apt-get install -y openssl

      - name: Generate Cosign keys
        run: |
          # Use printf to avoid trailing newline in the password
          printf "temp_password" | cosign generate-key-pair -y
          chmod 600 cosign.key cosign.pub

          # Decrypt the private key
          openssl pkey -in cosign.key -out cosign_unprotected.key -passin pass:temp_password
          mv cosign_unprotected.key cosign.key
          chmod 600 cosign.key

      - name: Commit Cosign keys to repository
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add cosign.key cosign.pub
          git commit -m "Add Cosign keys (private and public)"
          git push origin main
