name: Test Kyverno Policy with Kind

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test-kyverno-policy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Create Kind cluster
        run: |
          kind create cluster --name kyverno-test
          kubectl cluster-info --context kind-kyverno-test

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Install Kyverno using Helm
        run: |
          helm repo add kyverno https://kyverno.github.io/kyverno/
          helm repo update
          helm install kyverno kyverno/kyverno -n kyverno --create-namespace --set replicaCount=1

      - name: Wait for Kyverno pods to be ready
        run: |
          kubectl wait --namespace kyverno \
            --for=condition=available \
            --timeout=300s \
            deployment/kyverno

          kubectl wait --namespace kyverno \
            --for=condition=ready \
            --timeout=300s \
            pod -l app.kubernetes.io/name=kyverno

      - name: Create Secret for Cosign public key
        run: |
          kubectl create secret generic cosign-public-key --from-file=cosign.pub=./cosign.pub

      - name: Apply Kyverno policy
        run: |
          cat <<EOF | kubectl apply -f -
          apiVersion: kyverno.io/v1
          kind: ClusterPolicy
          metadata:
            name: verify-image-signatures
          spec:
            validationFailureAction: enforce
            background: false
            rules:
              - name: check-image-signature
                match:
                  any:
                  - resources:
                      kinds:
                        - Pod
                preconditions:
                  all:
                  - key: "{{ request.object.spec.containers[].image }}"
                    operator: AnyIn
                    value:
                      - ghcr.io/it-life1/**
                validate:
                  message: "Image is not signed or signature verification failed."
                  foreach:
                  - list: "request.object.spec.containers"
                    context:
                      - name: imageData
                        imageRegistry:
                          reference: "{{ element.image }}"
                          key: cosign-public-key # Corrected field name
                    deny:
                      conditions:
                        all:
                        - key: "{{ imageData.signatureVerified }}"
                          operator: Equals
                          value: false
          EOF

      - name: Deploy signed image
        run: |
          cat <<EOF | kubectl apply -f -
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: signed-deployment
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: signed
            template:
              metadata:
                labels:
                  app: signed
              spec:
                containers:
                - name: signed-container
                  image: ghcr.io/it-life1/dockertesting:signed-tag
          EOF
          kubectl wait --for=condition=available deployment/signed-deployment --timeout=300s

      - name: Deploy unsigned image
        run: |
          set +e
          cat <<EOF | kubectl apply -f -
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: unsigned-deployment
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: unsigned
            template:
              metadata:
                labels:
                  app: unsigned
              spec:
                containers:
                - name: unsigned-container
                  image: ghcr.io/it-life1/dockertesting:unsigned-tag
          EOF
          sleep 10
          kubectl get deployment unsigned-deployment && exit 1
          echo "Unsigned deployment blocked as expected"

      - name: Cleanup Kind cluster
        if: always()
        run: |
          kind delete cluster --name kyverno-test
